Management
algosup/2024-2025-project-2-serious-game-team-6 pull request #42
Opened 2024-12-20 10:09 UTC by MistzSoftware

This pull request includes several updates to the weekly reports and management artifacts in the documentation. The most important changes include adding detailed content for Week 7 in both the cumulative and individual weekly reports, and updating management artifacts with new links and a completed post-mortem section.

Updates to weekly reports:

* [`Documents/Management/WeeklyReports/cumulative.md`](diffhunk://#diff-a0017180b2348a9eb8abd8fa5784fc7bd54a7502e5bbf5941a5ab735c45e2fd5R421-R460): Added detailed sections for Week 7, including Overview, Accomplishments, Challenges, Plan for Next Week, Team Mood, and Conclusion.
* [`Documents/Management/WeeklyReports/week7.md`](diffhunk://#diff-d9450e13a2df79a8cd0a2745a45c32c58dff6b02dafda03d274a68062b6f3d9dR1-R41): Created a new file for Week 7 with comprehensive details on the week's activities, achievements, challenges, and future plans.

Updates to management artifacts:

* [`Documents/Management/managementArtifact.md`](diffhunk://#diff-b21ccb2a7a9148a56955a4e1131f85fa56f70b5baba801fae7706a4538d890f0R23): Added a link to the Gantt chart for better task visualization.
* [`Documents/Management/managementArtifact.md`](diffhunk://#diff-b21ccb2a7a9148a56955a4e1131f85fa56f70b5baba801fae7706a4538d890f0L86-L90): Completed the post-mortem section with detailed reflections from team members on their experiences, challenges, and learnings.

2024-12-20 10:34 UTC, EnzoGuillouche requested changes
Some issues have been spotted, and need to be solved before merging.

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/WeeklyReports/week7.md
> +   - Integrated all sprites, sounds, and game mechanics to enhance the user experience for the oral presentation.
oral presentation does not exist in English, just write final presentation.

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/WeeklyReports/week7.md
> +Moving forward, the planned vacation will give the team a much-needed opportunity to recharge and return refreshed for the next phase of the project. Overall, the week was a success, with key accompl
"to recharge" would need precisions. such as "to recharge their batteries"

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +You can Also find the gantt chart [HERE](https://sharing.clickup.com/9012521102/g/h/8ck0a4e-412/37cdcab5cca6985)
there's a capital letter at "also"

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Mathias<br>(SCRUM Master) | - Godot is very powerful<br> - Data about climat<br> - It's easier to keep a good workload when strict than when being a cool manager
"desipated" should be "dissipated"

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Mathias<br>(SCRUM Master) | - Godot is very powerful<br> - Data about climat<br> - It's easier to keep a good workload when strict than when being a cool manager
replace **childish** members by **mature** ones

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Mathias<br>(SCRUM Master) | - Godot is very powerful<br> - Data about climat<br> - It's easier to keep a good workload when strict than when being a cool manager
The fact that few team members **took** on them to

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Mathias<br>(SCRUM Master) | - Godot is very powerful<br> - Data about climat<br> - It's easier to keep a good workload when strict than when being a cool manager
there should be no 's' for "Being a cops"

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Enzo                      | - First time project manager<br> - Learnt how to do a functional and use code<br> - Learnt what was the climat changes<br> - Unknown data about recycling and climat chan
First time PROGRAM manager

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Enzo                      | - First time project manager<br> - Learnt how to do a functional and use code<br> - Learnt what was the climat changes<br> - Unknown data about recycling and climat chan
there should be no 's' for "climat changes"

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Enzo                      | - First time project manager<br> - Learnt how to do a functional and use code<br> - Learnt what was the climat changes<br> - Unknown data about recycling and climat chan
catch up the time waste**D** on the code

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Enzo                      | - First time project manager<br> - Learnt how to do a functional and use code<br> - Learnt what was the climat changes<br> - Unknown data about recycling and climat chan
I believe you meant "learn fast **how** to code in godot."

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Enzo                      | - First time project manager<br> - Learnt how to do a functional and use code<br> - Learnt what was the climat changes<br> - Unknown data about recycling and climat chan
there no 'e' for "development"

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Evan                      | - Godot<br> - Detailed data about climat changes
same about climate change

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Evan                      | - Godot<br> - Detailed data about climat changes
"decrease of motivation" would be better

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Evan                      | - Godot<br> - Detailed data about climat changes
'heal from sickness' would be better

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Michel                    | - How does a game engine works<br> - How to well setup a game engine<br> - How to use godot<br> - How to write a good and structured code (thanks to the TL)<BR> - how it
'How does a game engine works' there should not be a s for work

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Michel                    | - How does a game engine works<br> - How to well setup a game engine<br> - How to use godot<br> - How to write a good and structured code (thanks to the TL)<BR> - how it
"how difficult it is" would be better

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Loic                      | - How to use godot<br> - Data about climat changes<br> - how to communicate with the team.<br> - What is a serious game.
same about climate change

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Tino                      | - What is a serious game<br> - Godot is shit<br> - The importance of reviewing multiple time a file.
same for final presentation

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Tino                      | - What is a serious game<br> - Godot is shit<br> - The importance of reviewing multiple time a file.
"multiple times" would be better

2024-12-20 10:34 UTC, EnzoGuillouche commented on Documents/Management/managementArtifact.md
> +| Axel                      | - I learnt Godot<br> - How to write a user manual<br> - Learnt about what is a serious game.
"Didn't know" would be better

2024-12-22 09:36 UTC, MistzSoftware commented
all of these issue have been fixed in commit https://github.com/algosup/2024-2025-project-2-serious-game-team-6/pull/42/commits/95f4dfcfef524abf54e15b054ff1fbe9523d5cc3

2024-12-22 20:05 UTC, MistzSoftware commented
Forced merge because the QA deserted his post.

2024-12-22 20:05 UTC, merged